// data.js
const studyData = {
    verbs: [
        { dict: "Kiku", kanji: "聞く", eng: "Listen", group: 1, stem: "kiki" },
        { dict: "Oyogu", kanji: "泳ぐ", eng: "Swim", group: 1, stem: "oyogi" },
        { dict: "Hanasu", kanji: "話す", eng: "Talk", group: 1, stem: "hanashi" },
        { dict: "Yomu", kanji: "読む", eng: "Read", group: 1, stem: "yomi" },
        { dict: "Shinu", kanji: "死ぬ", eng: "Die", group: 1, stem: "shini" },
        { dict: "Yobu", kanji: "呼ぶ", eng: "Call", group: 1, stem: "yobi" },
        { dict: "Iu", kanji: "言う", eng: "Say", group: 1, stem: "ii" },
        { dict: "Matsu", kanji: "待つ", eng: "Wait", group: 1, stem: "machi" },
        { dict: "Toru", kanji: "取る", eng: "Take", group: 1, stem: "tori" },
        { dict: "Katsu", kanji: "勝つ", eng: "Win", group: 1, stem: "kachi" },
        { dict: "Au", kanji: "会う", eng: "Meet", group: 1, stem: "ai" },
        { dict: "Iku", kanji: "行く", eng: "Go", group: 1, stem: "iki" },
        { dict: "Nomu", kanji: "飲む", eng: "Drink", group: 1, stem: "nomi" },
        { dict: "Warau", kanji: "笑う", eng: "Laugh", group: 1, stem: "warai" },
        { dict: "Naku", kanji: "泣く", eng: "Cry", group: 1, stem: "naki" },
        { dict: "Odoru", kanji: "踊る", eng: "Dance", group: 1, stem: "odori" },
        { dict: "Kau", kanji: "買う", eng: "Buy", group: 1, stem: "kai" },
        { dict: "Tsukau", kanji: "使う", eng: "Use", group: 1, stem: "tsukai" },
        { dict: "Tsukuru", kanji: "作る", eng: "Make", group: 1, stem: "tsukuri" },
        { dict: "Kaku", kanji: "書く", eng: "Write", group: 1, stem: "kaki" },
        { dict: "Hashiru", kanji: "走る", eng: "Run", group: 1, stem: "hashi" },
        { dict: "Kaeru", kanji: "帰る", eng: "Return", group: 1, stem: "kaeri" },
        { dict: "Aru", kanji: "ある", eng: "Exist (inanimate)", group: 1, stem: "ari" },
        { dict: "Wakaru", kanji: "分かる", eng: "Understand", group: 1, stem: "wakari" },
        { dict: "Taberu", kanji: "食べる", eng: "Eat", group: 2, stem: "tabe" },
        { dict: "Neru", kanji: "寝る", eng: "Sleep", group: 2, stem: "ne" },
        { dict: "Miru", kanji: "見る", eng: "See", group: 2, stem: "mi" },
        { dict: "Okiru", kanji: "起きる", eng: "Wake", group: 2, stem: "oki" },
        { dict: "Oshieru", kanji: "教える", eng: "Teach", group: 2, stem: "oshie" },
        { dict: "Akeru", kanji: "開ける", eng: "Open", group: 2, stem: "ake" },
        { dict: "Shimeru", kanji: "閉める", eng: "Close", group: 2, stem: "shime" },
        { dict: "Oriru", kanji: "降りる", eng: "Get off", group: 2, stem: "ori" },
        { dict: "Iru", kanji: "いる", eng: "Exist (animate)", group: 2, stem: "i" },
        { dict: "Wasureru", kanji: "忘れる", eng: "Forget", group: 2, stem: "wasure" },
        { dict: "Suru", kanji: "する", eng: "Do", group: 3, stem: "shi" },
        { dict: "Kuru", kanji: "来る", eng: "Come", group: 3, stem: "ki" },
        { dict: "Benkyou suru", kanji: "勉強する", eng: "Study", group: 3, stem: "benkyoushi" },
        { dict: "Unten suru", kanji: "運転する", eng: "Drive", group: 3, stem: "untenshi" },
        { dict: "Kaimono suru", kanji: "買い物する", eng: "Shop", group: 3, stem: "kaimonoshi" },
        { dict: "Ryouri suru", kanji: "料理する", eng: "Cook", group: 3, stem: "ryourishi" },
        { dict: "Aruku", kanji: "歩く", eng: "Walk", group: 1, stem: "aruki" },
        { dict: "Hauru", kanji: "入る", eng: "Enter", group: 1, stem: "hairi" },
        { dict: "Dasu", kanji: "出す", eng: "Take out / Hand in", group: 1, stem: "dashi" },
        { dict: "Tatsu", kanji: "立つ", eng: "Stand up", group: 1, stem: "tachi" },
        { dict: "Suwaru", kanji: "座る", eng: "Sit", group: 1, stem: "suwari" },
        { dict: "Yannu", kanji: "やる", eng: "Do / Give (to subordinates)", group: 1, stem: "yari" },
        { dict: "Ageru", kanji: "あげる", eng: "Give", group: 2, stem: "age" },
        { dict: "Morau", kanji: "もらう", eng: "Receive", group: 1, stem: "morai" },
        { dict: "Kakeru", kanji: "かける", eng: "Make a call / Wear glasses", group: 2, stem: "kake" },
        { dict: "Kasu", kanji: "貸す", eng: "Lend", group: 1, stem: "kashi" },
        { dict: "Kariru", kanji: "借りる", eng: "Borrow", group: 2, stem: "kari" }
];
    ],
    adjectives: [
        { dict: "Oishii", kanji: "美味しい", eng: "Delicious", type: "i", stem: "oishi" },
        { dict: "Takai", kanji: "高い", eng: "Expensive", type: "i", stem: "taka" },
        { dict: "Yasui", kanji: "安い", eng: "Cheap", type: "i", stem: "yasu" },
        { dict: "Samui", kanji: "寒い", eng: "Cold", type: "i", stem: "samu" },
        { dict: "Kirei", kanji: "綺麗", eng: "Pretty", type: "na" },
        { dict: "Shizuka", kanji: "静か", eng: "Quiet", type: "na" },
        { dict: "Genki", kanji: "元気", eng: "Healthy", type: "na" },
        { dict: "Atarashii", kanji: "新しい", eng: "New", type: "i", stem: "atarashi" },
        { dict: "Furui", kanji: "古い", eng: "Old", type: "i", stem: "furu" },
        { dict: "Atsui", kanji: "暑い", eng: "Hot", type: "i", stem: "atsu" },
        { dict: "Omoshiroi", kanji: "面白い", eng: "Interesting", type: "i", stem: "omoshiroi" },
        { dict: "Chiisai", kanji: "小さい", eng: "Small", type: "i", stem: "chiisa" },
        { dict: "Ookii", kanji: "大きい", eng: "Big", type: "i", stem: "ooki" },
        { dict: "Hayai", kanji: "早い", eng: "Fast", type: "i", stem: "haya" },
        { dict: "Muzukashii", kanji: "難しい", eng: "Difficult", type: "i", stem: "muzukashi" },
        { dict: "Hima", kanji: "暇", eng: "Free (time)", type: "na" },
        { dict: "Suki", kanji: "好き", eng: "Like", type: "na" },
        { dict: "Kirai", kanji: "嫌い", eng: "Dislike", type: "na" },
        { dict: "Benri", kanji: "便利", eng: "Convenient", type: "na" },
        { dict: "Nigiyaka", kanji: "賑やか", eng: "Lively", type: "na" }
    ],
    time: [
        { dict: "Getsuyoubi", kanji: "月曜日", eng: "Monday" },
        { dict: "Kayoubi", kanji: "火曜日", eng: "Tuesday" },
        { dict: "Suiyoubi", kanji: "水曜日", eng: "Wednesday" },
        { dict: "Mokuyoubi", kanji: "木曜日", eng: "Thursday" },
        { dict: "Kinyoubi", kanji: "金曜日", eng: "Friday" },
        { dict: "Douyoubi", kanji: "土曜日", eng: "Saturday" },
        { dict: "Nichiyoubi", kanji: "日曜日", eng: "Sunday" },
        { dict: "Tsuitachi", kanji: "1日", eng: "1st" },
        { dict: "Futsuka", kanji: "2日", eng: "2nd" },
        { dict: "Mikka", kanji: "3日", eng: "3rd" },
        { dict: "Yokka", kanji: "4日", eng: "4th" },
        { dict: "Itsuka", kanji: "5日", eng: "5th" },
        { dict: "Muika", kanji: "6日", eng: "6th" },
        { dict: "Nanoka", kanji: "7日", eng: "7th" },
        { dict: "Youka", kanji: "8日", eng: "8th" },
        { dict: "Kokonoka", kanji: "9日", eng: "9th" },
        { dict: "Touka", kanji: "10日", eng: "10th" },
        { dict: "Ichigatsu", kanji: "1月", eng: "January" },
        { dict: "Nigatsu", kanji: "2月", eng: "February" },
        { dict: "Sangatsu", kanji: "3月", eng: "March" },
        { dict: "Shigatsu", kanji: "4月", eng: "April" },
        { dict: "Gogatsu", kanji: "5月", eng: "May" },
        { dict: "Rokugatsu", kanji: "6月", eng: "June" },
        { dict: "Shichigatsu", kanji: "7月", eng: "July" },
        { dict: "Hachigatsu", kanji: "8月", eng: "August" },
        { dict: "Kugatsu", kanji: "9月", eng: "September" },
        { dict: "Juugatsu", kanji: "10月", eng: "October" },
        { dict: "Juuichigatsu", kanji: "11月", eng: "November" },
        { dict: "Juunigatsu", kanji: "12月", eng: "December" },
        { dict: "Kyou", kanji: "今日", eng: "Today" },
        { dict: "Kinou", kanji: "昨日", eng: "Yesterday" },
        { dict: "Ashita", kanji: "明日", eng: "Tomorrow" },
        { dict: "Mainichi", kanji: "毎日", eng: "Every day" },
        { dict: "Itsumo", kanji: "いつも", eng: "Always" },
        { dict: "Kesa", kanji: "今朝", eng: "This morning" },
        { dict: "Konban", kanji: "今晩", eng: "This evening" },
        { dict: "Konshuu", kanji: "今週", eng: "This week" },
        { dict: "Senshuu", kanji: "先週", eng: "Last week" },
        { dict: "Raishuu", kanji: "来週", eng: "Next week" },
        { dict: "Kongetsu", kanji: "今月", eng: "This month" },
        { dict: "Sengetsu", kanji: "先月", eng: "Last month" },
        { dict: "Raigetsu", kanji: "来月", eng: "Next month" },
        { dict: "Kotoshi", kanji: "今年", eng: "This year" },
        { dict: "Kyonen", kanji: "去年", eng: "Last year" },
        { dict: "Rainen", kanji: "来年", eng: "Next year" },
        { dict: "Tokidoki", kanji: "時々", eng: "Sometimes" }
    ],
    vocab: [
        { dict: "Inu", kanji: "犬", eng: "Dog" },
        { dict: "Neko", kanji: "猫", eng: "Cat" },
        { dict: "Tori", kanji: "鳥", eng: "Bird" },
        { dict: "Sakana", kanji: "魚", eng: "Fish" },
        { dict: "Uma", kanji: "馬", eng: "Horse" },
        { dict: "Gohan", kanji: "ご飯", eng: "Rice" },
        { dict: "Niku", kanji: "肉", eng: "Meat" },
        { dict: "Yasai", kanji: "野菜", eng: "Vegetable" },
        { dict: "Ringo", kanji: "りんご", eng: "Apple" },
        { dict: "Tamago", kanji: "卵", eng: "Egg" },
        { dict: "Tamanegi", kanji: "玉ねぎ", eng: "Onion" },
        { dict: "Me", kanji: "目", eng: "Eye" },
        { dict: "Mimi", kanji: "耳", eng: "Ear" },
        { dict: "Kuchi", kanji: "口", eng: "Mouth" },
        { dict: "Te", kanji: "手", eng: "Hand" },
        { dict: "Ashi", kanji: "足", eng: "Foot" },
        { dict: "Atama", kanji: "頭", eng: "Head" }
    ],
    others: [
        { dict: "Arigatou", kanji: "ありがとう", eng: "Thank you" },
        { dict: "Konnichiwa", kanji: "こんにちは", eng: "Hello" }
    ]
};
