// data.js
const studyData = {
    verbs: [
        { dict: "Kiku", kanji: "聞く", eng: "Listen", group: 1, stem: "kiki" },
        { dict: "Oyogu", kanji: "泳ぐ", eng: "Swim", group: 1, stem: "oyogi" },
        { dict: "Hanasu", kanji: "話す", eng: "Talk", group: 1, stem: "hanashi" },
        { dict: "Yomu", kanji: "読む", eng: "Read", group: 1, stem: "yomi" },
        { dict: "Shinu", kanji: "死ぬ", eng: "Die", group: 1, stem: "shini" },
        { dict: "Yobu", kanji: "呼ぶ", eng: "Call", group: 1, stem: "yobi" },
        { dict: "Iu", kanji: "言う", eng: "Say", group: 1, stem: "ii" },
        { dict: "Matsu", kanji: "待つ", eng: "Wait", group: 1, stem: "machi" },
        { dict: "Toru", kanji: "取る", eng: "Take", group: 1, stem: "tori" },
        { dict: "Katsu", kanji: "勝つ", eng: "Win", group: 1, stem: "kachi" },
        { dict: "Au", kanji: "会う", eng: "Meet", group: 1, stem: "ai" },
        { dict: "Iku", kanji: "行く", eng: "Go", group: 1, stem: "iki" },
        { dict: "Nomu", kanji: "飲む", eng: "Drink", group: 1, stem: "nomi" },
        { dict: "Warau", kanji: "笑う", eng: "Laugh", group: 1, stem: "warai" },
        { dict: "Naku", kanji: "泣く", eng: "Cry", group: 1, stem: "naki" },
        { dict: "Odoru", kanji: "踊る", eng: "Dance", group: 1, stem: "odori" },
        { dict: "Kau", kanji: "買う", eng: "Buy", group: 1, stem: "kai" },
        { dict: "Tsukau", kanji: "使う", eng: "Use", group: 1, stem: "tsukai" },
        { dict: "Tsukuru", kanji: "作る", eng: "Make", group: 1, stem: "tsukuri" },
        { dict: "Kaku", kanji: "書く", eng: "Write", group: 1, stem: "kaki" },
        { dict: "Hashiru", kanji: "走る", eng: "Run", group: 1, stem: "hashi" },
        { dict: "Kaeru", kanji: "帰る", eng: "Return", group: 1, stem: "kaeri" },
        { dict: "Aru", kanji: "ある", eng: "Exist (inanimate)", group: 1, stem: "ari" },
        { dict: "Wakaru", kanji: "分かる", eng: "Understand", group: 1, stem: "wakari" },
        { dict: "Taberu", kanji: "食べる", eng: "Eat", group: 2, stem: "tabe" },
        { dict: "Neru", kanji: "寝る", eng: "Sleep", group: 2, stem: "ne" },
        { dict: "Miru", kanji: "見る", eng: "See", group: 2, stem: "mi" },
        { dict: "Okiru", kanji: "起きる", eng: "Wake", group: 2, stem: "oki" },
        { dict: "Oshieru", kanji: "教える", eng: "Teach", group: 2, stem: "oshie" },
        { dict: "Akeru", kanji: "開ける", eng: "Open", group: 2, stem: "ake" },
        { dict: "Shimeru", kanji: "閉める", eng: "Close", group: 2, stem: "shime" },
        { dict: "Oriru", kanji: "降りる", eng: "Get off", group: 2, stem: "ori" },
        { dict: "Iru", kanji: "いる", eng: "Exist (animate)", group: 2, stem: "i" },
        { dict: "Wasureru", kanji: "忘れる", eng: "Forget", group: 2, stem: "wasure" },
        { dict: "Suru", kanji: "する", eng: "Do", group: 3, stem: "shi" },
        { dict: "Kuru", kanji: "来る", eng: "Come", group: 3, stem: "ki" },
        { dict: "Benkyou suru", kanji: "勉強する", eng: "Study", group: 3, stem: "benkyoushi" },
        { dict: "Unten suru", kanji: "運転する", eng: "Drive", group: 3, stem: "untenshi" },
        { dict: "Kaimono suru", kanji: "買い物する", eng: "Shop", group: 3, stem: "kaimonoshi" },
        { dict: "Ryouri suru", kanji: "料理する", eng: "Cook", group: 3, stem: "ryourishi" },
        { dict: "Aruku", kanji: "歩く", eng: "Walk", group: 1, stem: "aruki" },
        { dict: "Hauru", kanji: "入る", eng: "Enter", group: 1, stem: "hairi" },
        { dict: "Dasu", kanji: "出す", eng: "Take out / Hand in", group: 1, stem: "dashi" },
        { dict: "Tatsu", kanji: "立つ", eng: "Stand up", group: 1, stem: "tachi" },
        { dict: "Suwaru", kanji: "座る", eng: "Sit", group: 1, stem: "suwari" },
        { dict: "Yannu", kanji: "やる", eng: "Do / Give (to subordinates)", group: 1, stem: "yari" },
        { dict: "Ageru", kanji: "あげる", eng: "Give", group: 2, stem: "age" },
        { dict: "Morau", kanji: "もらう", eng: "Receive", group: 1, stem: "morai" },
        { dict: "Kakeru", kanji: "かける", eng: "Make a call / Wear glasses", group: 2, stem: "kake" },
        { dict: "Kasu", kanji: "貸す", eng: "Lend", group: 1, stem: "kashi" },
        { dict: "Kariru", kanji: "借りる", eng: "Borrow", group: 2, stem: "kari" },
        { dict: "Kakaru", kanji: "掛かる", eng: "Take (time/money)", group: 1, stem: "kakari" }
    ],
    adjectives: [
        { dict: "Oishii", kanji: "美味しい", eng: "Delicious", type: "i", stem: "oishi" },
        { dict: "Takai", kanji: "高い", eng: "Expensive", type: "i", stem: "taka" },
        { dict: "Yasui", kanji: "安い", eng: "Cheap", type: "i", stem: "yasu" },
        { dict: "Samui", kanji: "寒い", eng: "Cold", type: "i", stem: "samu" },
        { dict: "Kirei", kanji: "綺麗", eng: "Pretty", type: "na" },
        { dict: "Shizuka", kanji: "静か", eng: "Quiet", type: "na" },
        { dict: "Genki", kanji: "元気", eng: "Healthy", type: "na" },
        { dict: "Atarashii", kanji: "新しい", eng: "New", type: "i", stem: "atarashi" },
        { dict: "Furui", kanji: "古い", eng: "Old", type: "i", stem: "furu" },
        { dict: "Atsui", kanji: "暑い", eng: "Hot", type: "i", stem: "atsu" },
        { dict: "Omoshiroi", kanji: "面白い", eng: "Interesting", type: "i", stem: "omoshiroi" },
        { dict: "Chiisai", kanji: "小さい", eng: "Small", type: "i", stem: "chiisa" },
        { dict: "Ookii", kanji: "大きい", eng: "Big", type: "i", stem: "ooki" },
        { dict: "Hayai", kanji: "早い", eng: "Fast", type: "i", stem: "haya" },
        { dict: "Muzukashii", kanji: "難しい", eng: "Difficult", type: "i", stem: "muzukashi" },
        { dict: "Hima", kanji: "暇", eng: "Free (time)", type: "na" },
        { dict: "Suki", kanji: "好き", eng: "Like", type: "na" },
        { dict: "Kirai", kanji: "嫌い", eng: "Dislike", type: "na" },
        { dict: "Benri", kanji: "便利", eng: "Convenient", type: "na" },
        { dict: "Nigiyaka", kanji: "賑やか", eng: "Lively", type: "na" },
        { dict: "Samui", kanji: "寒い", eng: "Cold (weather)", type: "i", stem: "samu" }, 
        { dict: "Tsumetai", kanji: "冷たい", eng: "Cold (to touch)", type: "i", stem: "tsumetai" },
        { dict: "Atatakai", kanji: "暖かい", eng: "Warm", type: "i", stem: "atataka" },
        { dict: "Suzushii", kanji: "涼しい", eng: "Cool", type: "i", stem: "suzushi" },
        { dict: "Toi", kanji: "遠い", eng: "Far", type: "i", stem: "toi" },
        { dict: "Chikai", kanji: "近い", eng: "Near", type: "i", stem: "chika" },
        { dict: "Ii", kanji: "いい", eng: "Good", type: "i", stem: "i" },
        { dict: "Warui", kanji: "悪い", eng: "Bad", type: "i", stem: "waru" },
        { dict: "Jouzu", kanji: "上手", eng: "Skillful / Good at", type: "na" },
        { dict: "Heta", kanji: "下手", eng: "Unskillful / Bad at", type: "na" },
        { dict: "Taihen", kanji: "大変", eng: "Tough / Difficult situation", type: "na" }
    ],
    time: [
        { dict: "Getsuyoubi", kanji: "月曜日", eng: "Monday" },
        { dict: "Kayoubi", kanji: "火曜日", eng: "Tuesday" },
        { dict: "Suiyoubi", kanji: "水曜日", eng: "Wednesday" },
        { dict: "Mokuyoubi", kanji: "木曜日", eng: "Thursday" },
        { dict: "Kinyoubi", kanji: "金曜日", eng: "Friday" },
        { dict: "Douyoubi", kanji: "土曜日", eng: "Saturday" },
        { dict: "Nichiyoubi", kanji: "日曜日", eng: "Sunday" },
        { dict: "Tsuitachi", kanji: "1日", eng: "1st" },
        { dict: "Futsuka", kanji: "2日", eng: "2nd" },
        { dict: "Mikka", kanji: "3日", eng: "3rd" },
        { dict: "Yokka", kanji: "4日", eng: "4th" },
        { dict: "Itsuka", kanji: "5日", eng: "5th" },
        { dict: "Muika", kanji: "6日", eng: "6th" },
        { dict: "Nanoka", kanji: "7日", eng: "7th" },
        { dict: "Youka", kanji: "8日", eng: "8th" },
        { dict: "Kokonoka", kanji: "9日", eng: "9th" },
        { dict: "Touka", kanji: "10日", eng: "10th" },
        { dict: "Ichigatsu", kanji: "1月", eng: "January" },
        { dict: "Nigatsu", kanji: "2月", eng: "February" },
        { dict: "Sangatsu", kanji: "3月", eng: "March" },
        { dict: "Shigatsu", kanji: "4月", eng: "April" },
        { dict: "Gogatsu", kanji: "5月", eng: "May" },
        { dict: "Rokugatsu", kanji: "6月", eng: "June" },
        { dict: "Shichigatsu", kanji: "7月", eng: "July" },
        { dict: "Hachigatsu", kanji: "8月", eng: "August" },
        { dict: "Kugatsu", kanji: "9月", eng: "September" },
        { dict: "Juugatsu", kanji: "10月", eng: "October" },
        { dict: "Juuichigatsu", kanji: "11月", eng: "November" },
        { dict: "Juunigatsu", kanji: "12月", eng: "December" },
        { dict: "Kyou", kanji: "今日", eng: "Today" },
        { dict: "Kinou", kanji: "昨日", eng: "Yesterday" },
        { dict: "Ashita", kanji: "明日", eng: "Tomorrow" },
        { dict: "Mainichi", kanji: "毎日", eng: "Every day" },
        { dict: "Itsumo", kanji: "いつも", eng: "Always" },
        { dict: "Kesa", kanji: "今朝", eng: "This morning" },
        { dict: "Konban", kanji: "今晩", eng: "This evening" },
        { dict: "Konshuu", kanji: "今週", eng: "This week" },
        { dict: "Senshuu", kanji: "先週", eng: "Last week" },
        { dict: "Raishuu", kanji: "来週", eng: "Next week" },
        { dict: "Kongetsu", kanji: "今月", eng: "This month" },
        { dict: "Sengetsu", kanji: "先月", eng: "Last month" },
        { dict: "Raigetsu", kanji: "来月", eng: "Next month" },
        { dict: "Kotoshi", kanji: "今年", eng: "This year" },
        { dict: "Kyonen", kanji: "去年", eng: "Last year" },
        { dict: "Rainen", kanji: "来年", eng: "Next year" },
        { dict: "Tokidoki", kanji: "時々", eng: "Sometimes" },
        { dict: "Jikan", kanji: "時間", eng: "Time / Hours (duration)" },
        { dict: "Fun", kanji: "分", eng: "Minute" },
        { dict: "Byou", kanji: "秒", eng: "Second" },
        { dict: "Shuukan", kanji: "週間", eng: "Weeks (duration)" },
        { dict: "Kagetsu", kanji: "ヶ月", eng: "Months (duration)" },
        { dict: "Nen", kanji: "年", eng: "Year / Years (duration)" },
        { dict: "Amari", kanji: "あまり", eng: "Not very much (used with negative)", type: "adverb" },
        { dict: "Zenzen", kanji: "全然", eng: "Not at all (used with negative)", type: "adverb" }, 
        { dict: "Ototoi", kanji: "一昨日", eng: "Two days ago" },
        { dict: "Asatte", kanji: "明後日", eng: "In two days / Day after tomorrow" },
        { dict: "Yuubata", kanji: "夕方", eng: "Evening / Dusk" },
        { dict: "Yoru", kanji: "夜", eng: "Night" },
        { dict: "Yuube", kanji: "夕べ", eng: "Last night" },
        { dict: "Sakuban", kanji: "昨晩", eng: "Last night (more formal)" },
        { dict: "Asa", kanji: "朝", eng: "Morning" },
        { dict: "Hiruma", kanji: "昼間", eng: "Daytime" },
        { dict: "Gogo", kanji: "午後", eng: "PM / Afternoon" },
        { dict: "Gozen", kanji: "午前", eng: "AM / Morning" },
        { dict: "Saikin", kanji: "最近", eng: "Recently" },
        { dict: "Shougo", kanji: "正午", eng: "Noon" },
        { dict: "Ji", kanji: "時", eng: "O'clock" },
        { dict: "Han", kanji: "半", eng: "Half (e.g., half past an hour)" },
        { dict: "Otoshi", kanji: "一昨年", eng: "Year before last" },
        { dict: "Sarainen", kanji: "再来年", eng: "Year after next" },
        { dict: "Saraishuu", kanji: "再来週", eng: "Week after next" },
        { dict: "Saraigetsu", kanji: "再来月", eng: "Month after next" }
    ],
    vocab: [
        { dict: "Inu", kanji: "犬", eng: "Dog" },
        { dict: "Neko", kanji: "猫", eng: "Cat" },
        { dict: "Tori", kanji: "鳥", eng: "Bird" },
        { dict: "Sakana", kanji: "魚", eng: "Fish" },
        { dict: "Uma", kanji: "馬", eng: "Horse" },
        { dict: "Gohan", kanji: "ご飯", eng: "Rice" },
        { dict: "Niku", kanji: "肉", eng: "Meat" },
        { dict: "Yasai", kanji: "野菜", eng: "Vegetable" },
        { dict: "Ringo", kanji: "りんご", eng: "Apple" },
        { dict: "Tamago", kanji: "卵", eng: "Egg" },
        { dict: "Tamanegi", kanji: "玉ねぎ", eng: "Onion" },
        { dict: "Me", kanji: "目", eng: "Eye" },
        { dict: "Mimi", kanji: "耳", eng: "Ear" },
        { dict: "Kuchi", kanji: "口", eng: "Mouth" },
        { dict: "Te", kanji: "手", eng: "Hand" },
        { dict: "Ashi", kanji: "足", eng: "Foot" },
        { dict: "Atama", kanji: "頭", eng: "Head" },
        { dict: "Ie", kanji: "家", eng: "House / Home" },
        { dict: "Gakkou", kanji: "学校", eng: "School" },
        { dict: "Eki", kanji: "駅", eng: "Station" },
        { dict: "Kyoushitsu", kanji: "教室", eng: "Classroom" },
        { dict: "Shokudou", kanji: "食堂", eng: "Cafeteria / Dining hall" },
        { dict: "Honya", kanji: "本屋", eng: "Bookstore" },
        { dict: "Kuruma", kanji: "車", eng: "Car" },
        { dict: "Densha", kanji: "電車", eng: "Train" },
        { dict: "Jitensha", kanji: "自転車", eng: "Bicycle" },
        { dict: "Keitai", kanji: "携帯", eng: "Cell phone" },
        { dict: "Hon", kanji: "本", eng: "Book" },
        { dict: "Kaban", kanji: "鞄", eng: "Bag / Briefcase" },
        { dict: "Hito", kanji: "人", eng: "Person" },
        { dict: "Tomodachi", kanji: "友達", eng: "Friend" },
        { dict: "Sensei", kanji: "先生", eng: "Teacher" },
        { dict: "Gakusei", kanji: "学生", eng: "Student" },
        { dict: "Nani", kanji: "何", eng: "What" },
        { dict: "Dare", kanji: "誰", eng: "Who" },
        { dict: "Doko", kanji: "どこ", eng: "Where" },
        { dict: "Itsu", kanji: "いつ", eng: "When" },
        { dict: "Doushite", kanji: "どうして", eng: "Why" },
        { dict: "Ikura", kanji: "いくら", eng: "How much (money)" },
        { dict: "Ikutsu", kanji: "いくつ", eng: "How many / How old" },
        { dict: "Arigatou", kanji: "ありがとう", eng: "Thank you" },
        { dict: "Konnichiwa", kanji: "こんにちは", eng: "Hello" }
    ],
    classifiers: [
        { dict: "Nin", kanji: "〜人", eng: "Counter for people" },
        { dict: "Tsu", kanji: "〜つ", eng: "General counter for objects (up to 10)" },
        { dict: "Ko", kanji: "〜個", eng: "Counter for small, round, or compact objects" },
        { dict: "Hon", kanji: "〜本", eng: "Counter for long, cylindrical objects (bottles, pens)" },
        { dict: "Mai", kanji: "〜枚", eng: "Counter for flat, thin objects (paper, shirts, plates)" },
        { dict: "Dai", kanji: "〜台", eng: "Counter for machines, vehicles, and appliances" },
        { dict: "Satsu", kanji: "〜冊", eng: "Counter for books, notebooks, and bound volumes" },
        { dict: "Hiki", kanji: "〜匹", eng: "Counter for small animals, insects, and fish" },
        { dict: "Tou", kanji: "〜頭", eng: "Counter for large animals (horses, cows, elephants)" },
        { dict: "Wa", kanji: "〜羽", eng: "Counter for birds and rabbits" },
        { dict: "Hai", kanji: "〜杯", eng: "Counter for cupfuls, glassfuls, or bowls" },
        { dict: "Kai", kanji: "〜回", eng: "Counter for occurrences, repetitions, or times" },
        { dict: "Kai", kanji: "〜階", eng: "Counter for building floors or stories" },
        { dict: "Soku", kanji: "〜足", eng: "Counter for pairs of footwear (shoes, socks)" },
        { dict: "Ken", kanji: "〜軒", eng: "Counter for houses, shops, or buildings" },
        { dict: "Chaku", kanji: "〜着", eng: "Counter for suits or sets of clothing" },
        { dict: "Mei", kanji: "〜名", eng: "Counter for people (polite/formal contexts)" },
        { dict: "Tsuu", kanji: "〜通", eng: "Counter for letters, emails, and documents" },
        { dict: "Kyoku", kanji: "〜曲", eng: "Counter for songs or musical pieces" },
        { dict: "Do", kanji: "〜度", eng: "Counter for frequency, temperature, or angles" },
        { dict: "Nen", kanji: "〜年", eng: "Counter for years or calendar years" },
        { dict: "Gatsu", kanji: "〜月", eng: "Counter for months of the year" },
        { dict: "Kagetsu", kanji: "〜ヶ月", eng: "Counter for month durations" },
        { dict: "Shuukan", kanji: "〜週間", eng: "Counter for week durations" },
        { dict: "Ji", kanji: "〜時", eng: "Counter for hours (time of day)" },
        { dict: "Jikan", kanji: "〜時間", eng: "Counter for hour durations" },
        { dict: "Fun / Pun", kanji: "〜分", eng: "Counter for minutes (duration or time)" },
        { dict: "Byou", kanji: "〜秒", eng: "Counter for seconds" },
        { dict: "Sai", kanji: "〜歳 / 才", eng: "Counter for age (years old)" },
        { dict: "Ban", kanji: "〜番", eng: "Counter for ordinal numbers (No. 1, No. 2, etc.)" },
        { dict: "Sara", kanji: "〜皿", eng: "Counter for plates, dishes, or courses" },
        { dict: "Ken", kanji: "〜件", eng: "Counter for matters, cases, events, or emails" }
    ],
    
    kanji: [
        // Numbers
        { dict: "Ichi", kanji: "一", eng: "One" },
        { dict: "Ni", kanji: "二", eng: "Two" },
        { dict: "San", kanji: "三", eng: "Three" },
        { dict: "Yon / Shi", kanji: "四", eng: "Four" },
        { dict: "Go", kanji: "五", eng: "Five" },
        { dict: "Roku", kanji: "六", eng: "Six" },
        { dict: "Nana / Shichi", kanji: "七", eng: "Seven" },
        { dict: "Hachi", kanji: "八", eng: "Eight" },
        { dict: "Kyuu / Ku", kanji: "九", eng: "Nine" },
        { dict: "Juu", kanji: "十", eng: "Ten" },
        { dict: "Hyaku", kanji: "百", eng: "Hundred" },
        { dict: "Sen", kanji: "千", eng: "Thousand" },
        { dict: "Man", kanji: "万", eng: "Ten Thousand" },
        { dict: "En", kanji: "円", eng: "Yen / Circle" },
    
        // Time and Calendar
        { dict: "Hi / Bi / Ka", kanji: "日", eng: "Day / Sun" },
        { dict: "Tsuki / Gatsu", kanji: "月", eng: "Month / Moon" },
        { dict: "Hi / Ka", kanji: "火", eng: "Fire" },
        { dict: "Mizu / Sui", kanji: "水", eng: "Water" },
        { dict: "Ki / Moku", kanji: "木", eng: "Tree / Wood" },
        { dict: "Kane / Kin", kanji: "金", eng: "Money / Gold" },
        { dict: "Tsuchi / Do", kanji: "土", eng: "Soil / Earth" },
        { dict: "Ima / Kon", kanji: "今", eng: "Now" },
        { dict: "Shuu", kanji: "週", eng: "Week" },
        { dict: "Toshi / Nen", kanji: "年", eng: "Year" },
        { dict: "Aida / Ma / Kan", kanji: "間", eng: "Interval / Between" },
        { dict: "Toki / Ji", kanji: "時", eng: "Time / Hour" },
        { dict: "Fun / Bun", kanji: "分", eng: "Minute / Understand" },
        { dict: "Han", kanji: "半", eng: "Half" },
        { dict: "Mae / Zen", kanji: "前", eng: "Before / Front" },
        { dict: "Ushiro / Ato / Go", kanji: "後", eng: "After / Behind" },
        { dict: "Asa / Chou", kanji: "朝", eng: "Morning" },
        { dict: "Hiru / Chuu", kanji: "昼", eng: "Noon / Daytime" },
        { dict: "Yoru / Ban", kanji: "夜", eng: "Night / Evening" },
    
        // Nature and Elements
        { dict: "Yama / San", kanji: "山", eng: "Mountain" },
        { dict: "Kawa / Sawa", kanji: "川", eng: "River" },
        { dict: "Ta / Da", kanji: "田", eng: "Rice Field" },
        { dict: "Sora / Kuu", kanji: "空", eng: "Sky / Empty" },
        { dict: "Ki / Ke", kanji: "気", eng: "Spirit / Energy" },
        { dict: "Ame / U", kanji: "雨", eng: "Rain" },
        { dict: "Umi / Kai", kanji: "海", eng: "Sea / Ocean" },
        { dict: "Kaze / Fuu", kanji: "風", eng: "Wind" },
        { dict: "Hana / Ka", kanji: "花", eng: "Flower" },
    
        // Directions and Positions
        { dict: "Ue / Jou", kanji: "上", eng: "Up / Above" },
        { dict: "Shita / Ka", kanji: "下", eng: "Down / Below" },
        { dict: "Migi / U", kanji: "右", eng: "Right" },
        { dict: "Hidari / Sa", kanji: "左", eng: "Left" },
        { dict: "Naka / Chuu", kanji: "中", eng: "Inside / Middle" },
        { dict: "Soto / Gai", kanji: "外", eng: "Outside" },
        { dict: "Kita / Hoku", kanji: "北", eng: "North" },
        { dict: "Minami / Nan", kanji: "南", eng: "South" },
        { dict: "Higashi / Tou", kanji: "東", eng: "East" },
        { dict: "Nishi / Sei", kanji: "西", eng: "West" },
    
        // People and Relationships
        { dict: "Hito / Jin / Nin", kanji: "人", eng: "Person" },
        { dict: "Onna / Jo", kanji: "女", eng: "Woman / Female" },
        { dict: "Otoko / Dan", kanji: "男", eng: "Man / Male" },
        { dict: "Ko / Shi", kanji: "子", eng: "Child" },
        { dict: "Chichi / Tou", kanji: "父", eng: "Father" },
        { dict: "Haha / Kaa", kanji: "母", eng: "Mother" },
        { dict: "Tomodachi / Yuu", kanji: "友", eng: "Friend" },
    
        // Body Parts
        { dict: "Me / Moku", kanji: "目", eng: "Eye" },
        { dict: "Mimi / Ji", kanji: "耳", eng: "Ear" },
        { dict: "Kuchi / Guchi", kanji: "口", eng: "Mouth" },
        { dict: "Te / Shu", kanji: "手", eng: "Hand" },
        { dict: "Ashi / Soku", kanji: "足", eng: "Foot / Leg" },
    
        // Verbs and Actions
        { dict: "Iku / Kou", kanji: "行", eng: "To Go" },
        { dict: "Kiru / Rai", kanji: "来", eng: "To Come" },
        { dict: "Kaeru / Ki", kanji: "帰", eng: "To Return" },
        { dict: "Taberu / Shoku", kanji: "食", eng: "To Eat" },
        { dict: "Nomu / In", kanji: "飲", eng: "To Drink" },
        { dict: "Miru / Ken", kanji: "見", eng: "To See / Watch" },
        { dict: "Kiku / Bun", kanji: "聞", eng: "To Hear / Listen" },
        { dict: "Yomu / Doku", kanji: "読", eng: "To Read" },
        { dict: "Kaku / Sho", kanji: "書", eng: "To Write" },
        { dict: "Hanasu / Wa", kanji: "話", eng: "To Talk / Speak" },
        { dict: "Kau / Bai", kanji: "買", eng: "To Buy" },
        { dict: "Au / Kai", kanji: "会", eng: "To Meet" },
        { dict: "Deru / Dasu / Shutsu", kanji: "出", eng: "To Exit / Go out" },
        { dict: "Iru / Nyuu", kanji: "入", eng: "To Enter" },
        { dict: "Tatsu / Ritsu", kanji: "立", eng: "To Stand" },
        { dict: "Yasumu / Кyuu", kanji: "休", eng: "To Rest / Holiday" },
    
        // Adjectives and Descriptions
        { dict: "Ookii / Dai", kanji: "大", eng: "Big" },
        { dict: "Chiisai / Shou", kanji: "小", eng: "Small" },
        { dict: "Atarashii / Shin", kanji: "新", eng: "New" },
        { dict: "Furui / Ko", kanji: "古", eng: "Old" },
        { dict: "Nagai / Chou", kanji: "長", eng: "Long / Chief" },
        { dict: "Takai / Kou", kanji: "高", eng: "High / Expensive" },
        { dict: "Yasui / An", kanji: "安", eng: "Cheap / Safe" },
        { dict: "Shiroi / Haku", kanji: "白", eng: "White" },
    
        // Everyday Places and Objects
        { dict: "Hon / Pon", kanji: "本", eng: "Book / Origin" },
        { dict: "Kuruma / Sha", kanji: "車", eng: "Car / Vehicle" },
        { dict: "Mizu / Sui", kanji: "水", eng: "Water" }, // duplicate safe category variant
        { dict: "Gakkou / Kou", kanji: "校", eng: "School" },
        { dict: "Manabu / Gaku", kanji: "学", eng: "Study / Learn" },
        { dict: "Ikiru / Sei", kanji: "生", eng: "Life / Student" },
        { dict: "Saki / Sen", kanji: "先", eng: "Ahead / Previous" },
        { dict: "Mise / Ten", kanji: "店", eng: "Shop / Store" },
        { dict: "Kuni / Koku", kanji: "国", eng: "Country" },
        { dict: "Nihon / Nichi", kanji: "日", eng: "Sun / Japan-element" },
        { dict: "Bun / Mon", kanji: "文", eng: "Writing / Culture" },
        { dict: "Ushi / Gyuu", kanji: "牛", eng: "Cow" },
        { dict: "Uma / Ba", kanji: "馬", eng: "Horse" },
        { dict: "Sakana / Gyo", kanji: "魚", eng: "Fish" },
        { dict: "Tori / Chou", kanji: "鳥", eng: "Bird" }
    ]

};

// Expose studyData globally to bypass ES module scoping / file loading latency
window.studyData = studyData;
