// data.js
const studyData = {
    verbs: [
        { dict: "Kiku", kanji: "聞く", eng: "Listen", group: 1, stem: "kiki" },
        { dict: "Oyogu", kanji: "泳ぐ", eng: "Swim", group: 1, stem: "oyogi" },
        { dict: "Hanasu", kanji: "話す", eng: "Talk", group: 1, stem: "hanashi" },
        { dict: "Yomu", kanji: "読む", eng: "Read", group: 1, stem: "yomi" },
        { dict: "Shinu", kanji: "死ぬ", eng: "Die", group: 1, stem: "shini" },
        { dict: "Yobu", kanji: "呼ぶ", eng: "Call", group: 1, stem: "yobi" },
        { dict: "Iu", kanji: "言う", eng: "Say", group: 1, stem: "ii" },
        { dict: "Matsu", kanji: "待つ", eng: "Wait", group: 1, stem: "machi" },
        { dict: "Toru", kanji: "取る", eng: "Take", group: 1, stem: "tori" },
        { dict: "Katsu", kanji: "勝つ", eng: "Win", group: 1, stem: "kachi" },
        { dict: "Au", kanji: "会う", eng: "Meet", group: 1, stem: "ai" },
        { dict: "Iku", kanji: "行く", eng: "Go", group: 1, stem: "iki" },
        { dict: "Nomu", kanji: "飲む", eng: "Drink", group: 1, stem: "nomi" },
        { dict: "Warau", kanji: "笑う", eng: "Laugh", group: 1, stem: "warai" },
        { dict: "Naku", kanji: "泣く", eng: "Cry", group: 1, stem: "naki" },
        { dict: "Odoru", kanji: "踊る", eng: "Dance", group: 1, stem: "odori" },
        { dict: "Kau", kanji: "買う", eng: "Buy", group: 1, stem: "kai" },
        { dict: "Tsukau", kanji: "使う", eng: "Use", group: 1, stem: "tsukai" },
        { dict: "Tsukuru", kanji: "作る", eng: "Make", group: 1, stem: "tsukuri" },
        { dict: "Kaku", kanji: "書く", eng: "Write", group: 1, stem: "kaki" },
        { dict: "Hashiru", kanji: "走る", eng: "Run", group: 1, stem: "hashi" },
        { dict: "Kaeru", kanji: "帰る", eng: "Return", group: 1, stem: "kaeri" },
        { dict: "Aru", kanji: "ある", eng: "Exist (inanimate)", group: 1, stem: "ari" },
        { dict: "Wakaru", kanji: "分かる", eng: "Understand", group: 1, stem: "wakari" },
        { dict: "Taberu", kanji: "食べる", eng: "Eat", group: 2, stem: "tabe" },
        { dict: "Neru", kanji: "寝る", eng: "Sleep", group: 2, stem: "ne" },
        { dict: "Miru", kanji: "見る", eng: "See", group: 2, stem: "mi" },
        { dict: "Okiru", kanji: "起きる", eng: "Wake", group: 2, stem: "oki" },
        { dict: "Oshieru", kanji: "教える", eng: "Teach", group: 2, stem: "oshie" },
        { dict: "Akeru", kanji: "開ける", eng: "Open", group: 2, stem: "ake" },
        { dict: "Shimeru", kanji: "閉める", eng: "Close", group: 2, stem: "shime" },
        { dict: "Oriru", kanji: "降りる", eng: "Get off", group: 2, stem: "ori" },
        { dict: "Iru", kanji: "いる", eng: "Exist (animate)", group: 2, stem: "i" },
        { dict: "Wasureru", kanji: "忘れる", eng: "Forget", group: 2, stem: "wasure" },
        { dict: "Suru", kanji: "する", eng: "Do", group: 3, stem: "shi" },
        { dict: "Kuru", kanji: "来る", eng: "Come", group: 3, stem: "ki" },
        { dict: "Benkyou suru", kanji: "勉強する", eng: "Study", group: 3, stem: "benkyoushi" },
        { dict: "Unten suru", kanji: "運転する", eng: "Drive", group: 3, stem: "untenshi" },
        { dict: "Kaimono suru", kanji: "買い物する", eng: "Shop", group: 3, stem: "kaimonoshi" },
        { dict: "Ryouri suru", kanji: "料理する", eng: "Cook", group: 3, stem: "ryourishi" },
        { dict: "Aruku", kanji: "歩く", eng: "Walk", group: 1, stem: "aruki" },
        { dict: "Hairu", kanji: "入る", eng: "Enter", group: 1, stem: "hairi" },
        { dict: "Dasu", kanji: "出す", eng: "Take out / Hand in", group: 1, stem: "dashi" },
        { dict: "Tatsu", kanji: "立つ", eng: "Stand up", group: 1, stem: "tachi" },
        { dict: "Suwaru", kanji: "座る", eng: "Sit", group: 1, stem: "suwari" },
        { dict: "Yaru", kanji: "やる", eng: "Do / Give (to subordinates)", group: 1, stem: "yari" },
        { dict: "Ageru", kanji: "あげる", eng: "Give", group: 2, stem: "age" },
        { dict: "Morau", kanji: "もらう", eng: "Receive", group: 1, stem: "morai" },
        { dict: "Kakeru", kanji: "かける", eng: "Make a call / Wear glasses", group: 2, stem: "kake" },
        { dict: "Kasu", kanji: "貸す", eng: "Lend", group: 1, stem: "kashi" },
        { dict: "Kariru", kanji: "借りる", eng: "Borrow", group: 2, stem: "kari" },
        { dict: "Kakaru", kanji: "掛かる", eng: "Take (time/money)", group: 1, stem: "kakari" }
    ],
    adjectives: [
        { dict: "Oishii", kanji: "美味しい", eng: "Delicious", type: "i", stem: "oishi" },
        { dict: "Takai", kanji: "高い", eng: "Expensive / High", type: "i", stem: "taka" },
        { dict: "Yasui", kanji: "安い", eng: "Cheap", type: "i", stem: "yasu" },
        { dict: "Samui", kanji: "寒い", eng: "Cold (weather)", type: "i", stem: "samu" },
        { dict: "Kirei", kanji: "綺麗", eng: "Pretty / Clean", type: "na", stem: "kirei" },
        { dict: "Shizuka", kanji: "静か", eng: "Quiet", type: "na", stem: "shizuka" },
        { dict: "Genki", kanji: "元気", eng: "Healthy", type: "na", stem: "genki" },
        { dict: "Atarashii", kanji: "新しい", eng: "New", type: "i", stem: "atarashi" },
        { dict: "Furui", kanji: "古い", eng: "Old", type: "i", stem: "furu" },
        { dict: "Atsui", kanji: "暑い", eng: "Hot (weather)", type: "i", stem: "atsu" },
        { dict: "Omoshiroi", kanji: "面白い", eng: "Interesting", type: "i", stem: "omoshiro" },
        { dict: "Chiisai", kanji: "小さい", eng: "Small", type: "i", stem: "chiisa" },
        { dict: "Ookii", kanji: "大きい", eng: "Big", type: "i", stem: "ooki" },
        { dict: "Hayai", kanji: "早い", eng: "Fast / Early", type: "i", stem: "haya" },
        { dict: "Muzukashii", kanji: "難しい", eng: "Difficult", type: "i", stem: "muzukashi" },
        { dict: "Hima", kanji: "暇", eng: "Free (time)", type: "na", stem: "hima" },
        { dict: "Suki", kanji: "好き", eng: "Like", type: "na", stem: "suki" },
        { dict: "Kirai", kanji: "嫌い", eng: "Dislike", type: "na", stem: "kirai" },
        { dict: "Benri", kanji: "便利", eng: "Convenient", type: "na", stem: "benri" },
        { dict: "Nigiyaka", kanji: "賑やか", eng: "Lively", type: "na", stem: "nigiyaka" },
        { dict: "Tsumetai", kanji: "冷たい", eng: "Cold (to touch)", type: "i", stem: "tsumeta" },
        { dict: "Atatakai", kanji: "暖かい", eng: "Warm", type: "i", stem: "atataka" },
        { dict: "Suzushii", kanji: "涼しい", eng: "Cool", type: "i", stem: "suzushi" },
        { dict: "Toi", kanji: "遠い", eng: "Far", type: "i", stem: "toi" },
        { dict: "Chikai", kanji: "近い", eng: "Near", type: "i", stem: "chika" },
        { dict: "Ii", kanji: "いい", eng: "Good", type: "i", stem: "i" },
        { dict: "Warui", kanji: "悪い", eng: "Bad", type: "i", stem: "waru" },
        { dict: "Jouzu", kanji: "上手", eng: "Skillful / Good at", type: "na", stem: "jouzu" },
        { dict: "Heta", kanji: "下手", eng: "Unskillful / Bad at", type: "na", stem: "heta" },
        { dict: "Taihen", kanji: "大変", eng: "Tough / Difficult situation", type: "na", stem: "taihen" }
    ],
    time: [
        { dict: "Getsuyoubi", kanji: "月曜日", eng: "Monday" },
        { dict: "Kayoubi", kanji: "火曜日", eng: "Tuesday" },
        { dict: "Suiyoubi", kanji: "水曜日", eng: "Wednesday" },
        { dict: "Mokuyoubi", kanji: "木曜日", eng: "Thursday" },
        { dict: "Kinyoubi", kanji: "金曜日", eng: "Friday" },
        { dict: "Douyoubi", kanji: "土曜日", eng: "Saturday" },
        { dict: "Nichiyoubi", kanji: "日曜日", eng: "Sunday" },
  // 1st – 10th (Unique Native Readings)
  { dict: "Tsuitachi", kanji: "1日", eng: "1st day of the month / 1 day" },
  { dict: "Futsuka", kanji: "2日", eng: "2nd / 2 days" },
  { dict: "Mikka", kanji: "3日", eng: "3rd / 3 days" },
  { dict: "Yokka", kanji: "4日", eng: "4th / 4 days" },
  { dict: "Itsuka", kanji: "5日", eng: "5th / 5 days" },
  { dict: "Muika", kanji: "6日", eng: "6th / 6 days" },
  { dict: "Nanoka", kanji: "7日", eng: "7th / 7 days" },
  { dict: "Youka", kanji: "8日", eng: "8th / 8 days" },
  { dict: "Kokonoka", kanji: "9日", eng: "9th / 9 days" },
  { dict: "Touka", kanji: "10日", eng: "10th / 10 days" },

  // Standard Examples (Number + nichi)
  { dict: "Juuichinichi", kanji: "11日", eng: "11th / 11 days" },
  { dict: "Juuninichi", kanji: "12日", eng: "12th / 12 days" },
  { dict: "Juusannichi", kanji: "13日", eng: "13th / 13 days" },

  // Irregular Exceptions (14th, 19th, 20th)
  { dict: "Juuyokka", kanji: "14日", eng: "14th / 14 days" },
  { dict: "Juugonichi", kanji: "15日", eng: "15th / 15 days" },
  { dict: "Juuku nichi / Juukunichi", kanji: "19日", eng: "19th / 19 days" },
  { dict: "Hatsuka", kanji: "20日", eng: "20th / 20 days" },

  // Irregular Exceptions (24th, 29th)
  { dict: "Nijuuyokka", kanji: "24日", eng: "24th / 24 days" },
  { dict: "Nijuuku nichi / Nijuukunichi", kanji: "29日", eng: "29th / 29 days" },

  // End of Month / Standard Pattern
  { dict: "Sanjuunichi", kanji: "30日", eng: "30th / 30 days" },
  { dict: "Sanjuuichinichi", kanji: "31日", eng: "31st / 31 days" },

  // Question Form
  { dict: "Nannichi", kanji: "何日", eng: "Which day / How many days" },


        { dict: "Ichigatsu", kanji: "1月", eng: "January" },
        { dict: "Nigatsu", kanji: "2月", eng: "February" },
        { dict: "Sangatsu", kanji: "3月", eng: "March" },
        { dict: "Shigatsu", kanji: "4月", eng: "April" },
        { dict: "Gogatsu", kanji: "5月", eng: "May" },
        { dict: "Rokugatsu", kanji: "6月", eng: "June" },
        { dict: "Shichigatsu", kanji: "7月", eng: "July" },
        { dict: "Hachigatsu", kanji: "8月", eng: "August" },
        { dict: "Kugatsu", kanji: "9月", eng: "September" },
        { dict: "Juugatsu", kanji: "10月", eng: "October" },
        { dict: "Juuichigatsu", kanji: "11月", eng: "November" },
        { dict: "Juunigatsu", kanji: "12月", eng: "December" },
        { dict: "Kyou", kanji: "今日", eng: "Today" },
        { dict: "Kinou", kanji: "昨日", eng: "Yesterday" },
        { dict: "Ashita", kanji: "明日", eng: "Tomorrow" },
        { dict: "Mainichi", kanji: "毎日", eng: "Every day" },
        { dict: "Itsumo", kanji: "いつも", eng: "Always" },
        { dict: "Kesa", kanji: "今朝", eng: "This morning" },
        { dict: "Konban", kanji: "今晩", eng: "This evening" },
        { dict: "Konshuu", kanji: "今週", eng: "This week" },
        { dict: "Senshuu", kanji: "先週", eng: "Last week" },
        { dict: "Raishuu", kanji: "来週", eng: "Next week" },
        { dict: "Kongetsu", kanji: "今月", eng: "This month" },
        { dict: "Sengetsu", kanji: "先月", eng: "Last month" },
        { dict: "Raigetsu", kanji: "来月", eng: "Next month" },
        { dict: "Kotoshi", kanji: "今年", eng: "This year" },
        { dict: "Kyonen", kanji: "去年", eng: "Last year" },
        { dict: "Rainen", kanji: "来年", eng: "Next year" },
        { dict: "Tokidoki", kanji: "時々", eng: "Sometimes" },
        { dict: "Jikan", kanji: "時間", eng: "Time / Hours (duration)" },
        { dict: "Fun", kanji: "分", eng: "Minute" },
        { dict: "Byou", kanji: "秒", eng: "Second" },
        { dict: "Shuukan", kanji: "週間", eng: "Weeks (duration)" },
        { dict: "Kagetsu", kanji: "ヶ月", eng: "Months (duration)" },
        { dict: "Nen", kanji: "年", eng: "Year / Years (duration)" },
        { dict: "Ototoi", kanji: "一昨日", eng: "Two days ago" },
        { dict: "Asatte", kanji: "明後日", eng: "In two days / Day after tomorrow" },
        { dict: "Yuubata", kanji: "夕方", eng: "Evening / Dusk" },
        { dict: "Yoru", kanji: "夜", eng: "Night" },
        { dict: "Yuube", kanji: "夕べ", eng: "Last night" },
        { dict: "Sakuban", kanji: "昨晩", eng: "Last night (more formal)" },
        { dict: "Asa", kanji: "朝", eng: "Morning" },
        { dict: "Hiruma", kanji: "昼間", eng: "Daytime" },
        { dict: "Gogo", kanji: "午後", eng: "PM / Afternoon" },
        { dict: "Gozen", kanji: "午前", eng: "AM / Morning" },
        { dict: "Saikin", kanji: "最近", eng: "Recently" },
        { dict: "Shougo", kanji: "正午", eng: "Noon" },
        { dict: "Ji", kanji: "時", eng: "O'clock" },
        { dict: "Han", kanji: "半", eng: "Half (e.g., half past an hour)" },
        { dict: "Kyonen", kanji: "去年", eng: "Last year" }, // Fixed duplication from Otoshi typo
        { dict: "Sarainen", kanji: "再来年", eng: "Year after next" },
        { dict: "Saraishuu", kanji: "再来週", eng: "Week after next" },
        { dict: "Saraigetsu", kanji: "再来月", eng: "Month after next" }
    ],
    vocab: [
        { dict: "Inu", kanji: "犬", eng: "Dog" },
        { dict: "Neko", kanji: "猫", eng: "Cat" },
        { dict: "Tori", kanji: "鳥", eng: "Bird" },
        { dict: "Sakana", kanji: "魚", eng: "Fish" },
        { dict: "Uma", kanji: "馬", eng: "Horse" },
        { dict: "Gohan", kanji: "ご飯", eng: "Rice" },
        { dict: "Niku", kanji: "肉", eng: "Meat" },
        { dict: "Yasai", kanji: "野菜", eng: "Vegetable" },
        { dict: "Ringo", kanji: "りんご", eng: "Apple" },
        { dict: "Tamago", kanji: "卵", eng: "Egg" },
        { dict: "Tamanegi", kanji: "玉ねぎ", eng: "Onion" },
        { dict: "Me", kanji: "目", eng: "Eye" },
        { dict: "Mimi", kanji: "耳", eng: "Ear" },
        { dict: "Kuchi", kanji: "口", eng: "Mouth" },
        { dict: "Te", kanji: "手", eng: "Hand" },
        { dict: "Ashi", kanji: "足", eng: "Foot" },
        { dict: "Atama", kanji: "頭", eng: "Head" },
        { dict: "Ie", kanji: "家", eng: "House / Home" },
        { dict: "Gakkou", kanji: "学校", eng: "School" },
        { dict: "Eki", kanji: "駅", eng: "Station" },
        { dict: "Kyoushitsu", kanji: "教室", eng: "Classroom" },
        { dict: "Shokudou", kanji: "食堂", eng: "Cafeteria / Dining hall" },
        { dict: "Honya", kanji: "本屋", eng: "Bookstore" },
        { dict: "Kuruma", kanji: "車", eng: "Car" },
        { dict: "Densha", kanji: "電車", eng: "Train" },
        { dict: "Jitensha", kanji: "自転車", eng: "Bicycle" },
        { dict: "Keitai", kanji: "携帯", eng: "Cell phone" },
        { dict: "Hon", kanji: "本", eng: "Book" },
        { dict: "Kaban", kanji: "鞄", eng: "Bag / Briefcase" },
        { dict: "Hito", kanji: "人", eng: "Person" },
        { dict: "Tomodachi", kanji: "友達", eng: "Friend" },
        { dict: "Sensei", kanji: "先生", eng: "Teacher" },
        { dict: "Gakusei", kanji: "学生", eng: "Student" },
        { dict: "Amari", kanji: "あまり", eng: "Not very much (used with negative)", type: "adverb" },
        { dict: "Zenzen", kanji: "全然", eng: "Not at all (used with negative)", type: "adverb" },
        { dict: "Nani", kanji: "何", eng: "What" },
        { dict: "Dare", kanji: "誰", eng: "Who" },
        { dict: "Doko", kanji: "どこ", eng: "Where" },
        { dict: "Itsu", kanji: "いつ", eng: "When" },
        { dict: "Doushite", kanji: "どうして", eng: "Why" },
        { dict: "Ikura", kanji: "いくら", eng: "How much (money)" },
        { dict: "Ikutsu", kanji: "いくつ", eng: "How many / How old" },
        { dict: "Arigatou", kanji: "ありがとう", eng: "Thank you" },
        { dict: "Konnichiwa", kanji: "こんにちは", eng: "Hello" }
    ],
    classifiers: [
  // 1. General Objects (つ - Tsu)
  { dict: "Hitotsu", kanji: "一つ / 1つ", eng: "1 object" },
  { dict: "Futatsu", kanji: "二つ / 2つ", eng: "2 objects" },
  { dict: "Mittsu", kanji: "三つ / 3つ", eng: "3 objects" },
  { dict: "Yottsu", kanji: "四つ / 4つ", eng: "4 objects" },
  { dict: "Itsutsu", kanji: "五つ / 5つ", eng: "5 objects" },
  { dict: "Muttsu", kanji: "六つ / 6つ", eng: "6 objects" },
  { dict: "Nanatsu", kanji: "七つ / 7つ", eng: "7 objects" },
  { dict: "Yatsu", kanji: "八つ / 8つ", eng: "8 objects" },
  { dict: "Kokonotsu", kanji: "九つ / 9つ", eng: "9 objects" },
  { dict: "Too", kanji: "十 / 10", eng: "10 objects" },
  { dict: "Ikutsu", kanji: "いくつ", eng: "How many objects?" },

  // 2. People (人 - Nin)
  { dict: "Hitori", kanji: "一人 / 1人", eng: "1 person" },
  { dict: "Futari", kanji: "二人 / 2人", eng: "2 people" },
  { dict: "Sannin", kanji: "三人 / 3人", eng: "3 people" },
  { dict: "Yonin", kanji: "四人 / 4人", eng: "4 people" },
  { dict: "Gonin", kanji: "五人 / 5人", eng: "5 people" },
  { dict: "Rokunin", kanji: "六人 / 6人", eng: "6 people" },
  { dict: "Nananin", kanji: "七人 / 7人", eng: "7 people" },
  { dict: "Hachinin", kanji: "八人 / 8人", eng: "8 people" },
  { dict: "Kyuunin", kanji: "九人 / 9人", eng: "9 people" },
  { dict: "Juunin", kanji: "十人 / 10人", eng: "10 people" },
  { dict: "Nannin", kanji: "何人", eng: "How many people?" },

  // 3. Long Cylindrical Objects (本 - Hon)
  { dict: "Ippon", kanji: "一本 / 1本", eng: "1 long object (pen/bottle)" },
  { dict: "Nihon", kanji: "二本 / 2本", eng: "2 long objects" },
  { dict: "Sambon", kanji: "三本 / 3本", eng: "3 long objects" },
  { dict: "Yonhon", kanji: "四本 / 4本", eng: "4 long objects" },
  { dict: "Gohon", kanji: "五本 / 5本", eng: "5 long objects" },
  { dict: "Roppon", kanji: "六本 / 6本", eng: "6 long objects" },
  { dict: "Nanahon", kanji: "七本 / 7本", eng: "7 long objects" },
  { dict: "Happon", kanji: "八本 / 8本", eng: "8 long objects" },
  { dict: "Kyuuhon", kanji: "九本 / 9本", eng: "9 long objects" },
  { dict: "Juppon", kanji: "十本 / 10本", eng: "10 long objects" },
  { dict: "Nambon", kanji: "何本", eng: "How many long objects?" },

  // 4. Small Objects (個 - Ko)
  { dict: "Ikko", kanji: "一個 / 1個", eng: "1 small object" },
  { dict: "Niko", kanji: "二個 / 2個", eng: "2 small objects" },
  { dict: "Sanko", kanji: "三個 / 3個", eng: "3 small objects" },
  { dict: "Yonko", kanji: "四個 / 4個", eng: "4 small objects" },
  { dict: "Goko", kanji: "五個 / 5個", eng: "5 small objects" },
  { dict: "Rokko", kanji: "六個 / 6個", eng: "6 small objects" },
  { dict: "Nanako", kanji: "七個 / 7個", eng: "7 small objects" },
  { dict: "Hakko", kanji: "八個 / 8個", eng: "8 small objects" },
  { dict: "Kyuuko", kanji: "九個 / 9個", eng: "9 small objects" },
  { dict: "Jukko", kanji: "十個 / 10個", eng: "10 small objects" },

  // 5. Flat Objects (枚 - Mai)
  { dict: "Ichimai", kanji: "一枚 / 1枚", eng: "1 flat object (paper/shirt)" },
  { dict: "Nimai", kanji: "二枚 / 2枚", eng: "2 flat objects" },
  { dict: "Sammai", kanji: "三枚 / 3枚", eng: "3 flat objects" },
  { dict: "Yonmai", kanji: "四枚 / 4枚", eng: "4 flat objects" },
  { dict: "Gomai", kanji: "五枚 / 5枚", eng: "5 flat objects" },

  // 6. Books (冊 - Satsu)
  { dict: "Issatsu", kanji: "一冊 / 1冊", eng: "1 book/notebook" },
  { dict: "Nisatsu", kanji: "二冊 / 2冊", eng: "2 books" },
  { dict: "Sansatsu", kanji: "三冊 / 3冊", eng: "3 books" },

  // 7. Small Animals (匹 - Hiki)
  { dict: "Ippiki", kanji: "一匹 / 1匹", eng: "1 small animal" },
  { dict: "Nihiki", kanji: "二匹 / 2匹", eng: "2 small animals" },
  { dict: "Sambiki", kanji: "三匹 / 3匹", eng: "3 small animals" },

  // 8. Cups / Bowls (杯 - Hai)
  { dict: "Ippai", kanji: "一杯 / 1杯", eng: "1 cupful / glassful" },
  { dict: "Nihai", kanji: "二杯 / 2杯", eng: "2 cupfuls" },
  { dict: "Sambai", kanji: "三杯 / 3杯", eng: "3 cupfuls" },

  // 9. Minutes (分 - Fun)
  { dict: "Ippun", kanji: "1分", eng: "1 minute" },
  { dict: "Nifun", kanji: "2分", eng: "2 minutes" },
  { dict: "Sampun", kanji: "3分", eng: "3 minutes" },
  { dict: "Yompun", kanji: "4分", eng: "4 minutes" },
  { dict: "Gofun", kanji: "5分", eng: "5 minutes" },
  { dict: "Roppun", kanji: "6 minutes", eng: "6 minutes" },
  { dict: "Happun", kanji: "8分", eng: "8 minutes" },
  { dict: "Juppun", kanji: "10分", eng: "10 minutes" },

  // 10. Hours (時 - Ji)
  { dict: "Ichiji", kanji: "1時", eng: "1 o'clock" },
  { dict: "Niji", kanji: "2時", eng: "2 o'clock" },
  { dict: "Sanji", kanji: "3時", eng: "3 o'clock" },
  { dict: "Yoji", kanji: "4時", eng: "4 o'clock" },
  { dict: "Goji", kanji: "5時", eng: "5 o'clock" },
  { dict: "Rokuji", kanji: "6時", eng: "6 o'clock" },
  { dict: "Shichiji", kanji: "7時", eng: "7 o'clock" },
  { dict: "Hachiji", kanji: "8時", eng: "8 o'clock" },
  { dict: "Kuji", kanji: "9時", eng: "9 o'clock" },
  { dict: "Juuji", kanji: "10時", eng: "10 o'clock" },

  // 11. Age (歳 - Sai)
  { dict: "Issai", kanji: "1歳", eng: "1 year old" },
  { dict: "Nisai", kanji: "2歳", eng: "2 years old" },
  { dict: "Hatachi", kanji: "20歳 / 二十歳", eng: "20 years old" }
],

    kanji: [
        { dict: "Ichi", kanji: "一", eng: "One" },
        { dict: "Ni", kanji: "二", eng: "Two" },
        { dict: "San", kanji: "三", eng: "Three" },
        { dict: "Yon / Shi", kanji: "四", eng: "Four" },
        { dict: "Go", kanji: "五", eng: "Five" },
        { dict: "Roku", kanji: "六", eng: "Six" },
        { dict: "Nana / Shichi", kanji: "七", eng: "Seven" },
        { dict: "Hachi", kanji: "八", eng: "Eight" },
        { dict: "Kyuu / Ku", kanji: "九", eng: "Nine" },
        { dict: "Juu", kanji: "十", eng: "Ten" },
        { dict: "Hyaku", kanji: "百", eng: "Hundred" },
        { dict: "Sen", kanji: "千", eng: "Thousand" },
        { dict: "Man", kanji: "万", eng: "Ten Thousand" },
        { dict: "En", kanji: "円", eng: "Yen / Circle" },
        { dict: "Hi / Bi / Ka", kanji: "日", eng: "Day / Sun" },
        { dict: "Tsuki / Gatsu", kanji: "月", eng: "Month / Moon" },
        { dict: "Hi / Ka", kanji: "火", eng: "Fire" },
        { dict: "Mizu / Sui", kanji: "水", eng: "Water" },
        { dict: "Ki / Moku", kanji: "木", eng: "Tree / Wood" },
        { dict: "Kane / Kin", kanji: "金", eng: "Money / Gold" },
        { dict: "Tsuchi / Do", kanji: "土", eng: "Soil / Earth" },
        { dict: "Ima / Kon", kanji: "今", eng: "Now" },
        { dict: "Shuu", kanji: "週", eng: "Week" },
        { dict: "Toshi / Nen", kanji: "年", eng: "Year" },
        { dict: "Aida / Ma / Kan", kanji: "間", eng: "Interval / Between" },
        { dict: "Toki / Ji", kanji: "時", eng: "Time / Hour" },
        { dict: "Fun / Bun", kanji: "分", eng: "Minute / Understand" },
        { dict: "Han", kanji: "半", eng: "Half" },
        { dict: "Asa / Chou", kanji: "朝", eng: "Morning" },
        { dict: "Hiru / Chuu", kanji: "昼", eng: "Noon / Daytime" },
        { dict: "Yoru / Ban", kanji: "夜", eng: "Night / Evening" },
        { dict: "Yama / San", kanji: "山", eng: "Mountain" },
        { dict: "Kawa / Sawa", kanji: "川", eng: "River" },
        { dict: "Ta / Da", kanji: "田", eng: "Rice Field" },
        { dict: "Sora / Kuu", kanji: "空", eng: "Sky / Empty" },
        { dict: "Ki / Ke", kanji: "気", eng: "Spirit / Energy" },
        { dict: "Ame / U", kanji: "雨", eng: "Rain" },
        { dict: "Umi / Kai", kanji: "海", eng: "Sea / Ocean" },
        { dict: "Kaze / Fuu", kanji: "風", eng: "Wind" },
        { dict: "Hana / Ka", kanji: "花", eng: "Flower" },
        { dict: "Ue / Jou", kanji: "上", eng: "Up / Above" },
        { dict: "Shita / Ka", kanji: "下", eng: "Down / Below" },
        { dict: "Migi / U", kanji: "右", eng: "Right" },
        { dict: "Hidari / Sa", kanji: "左", eng: "Left" },
        { dict: "Naka / Chuu", kanji: "中", eng: "Inside / Middle" },
        { dict: "Soto / Gai", kanji: "外", eng: "Outside" },
        { dict: "Mae / Zen", kanji: "前", eng: "Before / Front" },
        { dict: "Ushiro / Ato / Go", kanji: "後", eng: "After / Behind" },
        { dict: "Kita / Hoku", kanji: "北", eng: "North" },
        { dict: "Minami / Nan", kanji: "南", eng: "South" },
        { dict: "Higashi / Tou", kanji: "東", eng: "East" },
        { dict: "Nishi / Sei", kanji: "西", eng: "West" },
        { dict: "Hito / Jin / Nin", kanji: "人", eng: "Person" },
        { dict: "Onna / Jo", kanji: "女", eng: "Woman / Female" },
        { dict: "Otoko / Dan", kanji: "男", eng: "Man / Male" },
        { dict: "Ko / Shi", kanji: "子", eng: "Child" },
        { dict: "Chichi / Tou", kanji: "父", eng: "Father" },
        { dict: "Haha / Kaa", kanji: "母", eng: "Mother" },
        { dict: "Tomodachi / Yuu", kanji: "友", eng: "Friend" },
        { dict: "Me / Moku", kanji: "目", eng: "Eye" },
        { dict: "Mimi / Ji", kanji: "耳", eng: "Ear" },
        { dict: "Kuchi / Guchi", kanji: "口", eng: "Mouth" },
        { dict: "Te / Shu", kanji: "手", eng: "Hand" },
        { dict: "Ashi / Soku", kanji: "足", eng: "Foot / Leg" },
        { dict: "Iku / Kou", kanji: "行", eng: "To Go" },
        { dict: "Kiru / Rai", kanji: "来", eng: "To Come" },
        { dict: "Kaeru / Ki", kanji: "帰", eng: "To Return" },
        { dict: "Taberu / Shoku", kanji: "食", eng: "To Eat" },
        { dict: "Nomu / In", kanji: "飲", eng: "To Drink" },
        { dict: "Miru / Ken", kanji: "見", eng: "To See / Watch" },
        { dict: "Kiku / Bun", kanji: "聞", eng: "To Hear / Listen" },
        { dict: "Yomu / Doku", kanji: "読", eng: "To Read" },
        { dict: "Kaku / Sho", kanji: "書", eng: "To Write" },
        { dict: "Hanasu / Wa", kanji: "話", eng: "To Talk / Speak" },
        { dict: "Kau / Bai", kanji: "買", eng: "To Buy" },
        { dict: "Au / Kai", kanji: "会", eng: "To Meet" },
        { dict: "Deru / Dasu / Shutsu", kanji: "出", eng: "To Exit / Go out" },
        { dict: "Iru / Nyuu", kanji: "入", eng: "To Enter" },
        { dict: "Tatsu / Ritsu", kanji: "立", eng: "To Stand" },
        { dict: "Yasumu / Kyuu", kanji: "休", eng: "To Rest / Holiday" }, // Fixed cyrillic K typo
        { dict: "Ookii / Dai", kanji: "大", eng: "Big" },
        { dict: "Chiisai / Shou", kanji: "小", eng: "Small" },
        { dict: "Atarashii / Shin", kanji: "新", eng: "New" },
        { dict: "Furui / Ko", kanji: "古", eng: "Old" },
        { dict: "Nagai / Chou", kanji: "長", eng: "Long / Chief" },
        { dict: "Takai / Kou", kanji: "高", eng: "High / Expensive" },
        { dict: "Yasui / An", kanji: "安", eng: "Cheap / Safe" },
        { dict: "Shiroi / Haku", kanji: "白", eng: "White" },
        { dict: "Hon / Pon", kanji: "本", eng: "Book / Origin" },
        { dict: "Kuruma / Sha", kanji: "車", eng: "Car / Vehicle" },
        { dict: "Gakkou / Kou", kanji: "校", eng: "School" },
        { dict: "Manabu / Gaku", kanji: "学", eng: "Study / Learn" },
        { dict: "Ikiru / Sei", kanji: "生", eng: "Life / Student" },
        { dict: "Saki / Sen", kanji: "先", eng: "Ahead / Previous" },
        { dict: "Mise / Ten", kanji: "店", eng: "Shop / Store" },
        { dict: "Kuni / Koku", kanji: "国", eng: "Country" },
        { dict: "Nihon / Nichi", kanji: "日", eng: "Sun / Japan-element" },
        { dict: "Bun / Mon", kanji: "文", eng: "Writing / Culture" },
        { dict: "Ushi / Gyuu", kanji: "牛", eng: "Cow" },
        { dict: "Uma / Ba", kanji: "馬", eng: "Horse" },
        { dict: "Sakana / Gyo", kanji: "魚", eng: "Fish" },
        { dict: "Tori / Chou", kanji: "鳥", eng: "Bird" }
    ],
    katakana: [
        { dict: "Koohii", kanji: "コーヒー", eng: "Coffee" },
        { dict: "Biiru", kanji: "ビール", eng: "Beer" },
        { dict: "Wain", kanji: "ワイン", eng: "Wine" },
        { dict: "Resutoran", kanji: "レストラン", eng: "Restaurant" },
        { dict: "Hoteru", kanji: "ホテル", eng: "Hotel" },
        { dict: "Depaato", kanji: "デパート", eng: "Department Store" },
        { dict: "Suupaa", kanji: "スーパー", eng: "Supermarket" },
        { dict: "Terebi", kanji: "テレビ", eng: "Television" },
        { dict: "Rajio", kanji: "ラジオ", eng: "Radio" },
        { dict: "Pasokon", kanji: "パソコン", eng: "Personal computer / PC" },
        { dict: "Sumaho", kanji: "スマホ", eng: "Smartphone" },
        { dict: "Kamera", kanji: "カメラ", eng: "Camera" },
        { dict: "Eakon", kanji: "エアコン", eng: "Air conditioner" },
        { dict: "Erebeetaa", kanji: "エレベーター", eng: "Elevator" },
        { dict: "Esukareetaa", kanji: "エスカレーター", eng: "Escalator" },
        { dict: "Toire", kanji: "トイレ", eng: "Toilet / Restroom" },
        { dict: "Shawaa", kanji: "シャワー", eng: "Shower" },
        { dict: "Beddo", kanji: "ベッド", eng: "Bed" },
        { dict: "Teeburu", kanji: "テーブル", eng: "Table" },
        { dict: "Sofaa", kanji: "ソファ", eng: "Sofa / Couch" },
        { dict: "Kappu", kanji: "カップ", eng: "Cup" },
        { dict: "Supuun", kanji: "スプーン", eng: "Spoon" },
        { dict: "Fooku", kanji: "フォーク", eng: "Fork" },
        { dict: "Naifu", kanji: "ナイフ", eng: "Knife" },
        { dict: "Pan", kanji: "パン", eng: "Bread" },
        { dict: "Bataa", kanji: "バター", eng: "Butter" },
        { dict: "Chiizu", kanji: "チーズ", eng: "Cheese" },
        { dict: "Sarada", kanji: "サラダ", eng: "Salad" },
        { dict: "Aisu Kuriimu", kanji: "アイスクリーム", eng: "Ice cream" },
        { dict: "Keeki", kanji: "ケーキ", eng: "Cake" },
        { dict: "Skaato", kanji: "スカート", eng: "Skirt" },
        { dict: "Tee-shatsu", kanji: "Tシャツ", eng: "T-shirt" },
        { dict: "Zubon", kanji: "ズボン", eng: "Trousers / Pants" },
        { dict: "Kooto", kanji: "コート", eng: "Coat" },
        { dict: "Nekutai", kanji: "ネクタイ", eng: "Necktie" },
        { dict: "Supootsu", kanji: "スポーツ", eng: "Sports" },
        { dict: "Sakkaa", kanji: "サッカー", eng: "Soccer / Football" },
        { dict: "Tenisu", kanji: "テニス", eng: "Tennis" },
        { dict: "Gitaa", kanji: "ギター", eng: "Guitar" },
        { dict: "Piano", kanji: "ピアノ", eng: "Piano" },
        { dict: "Nyuusu", kanji: "ニュース", eng: "News" },
        { dict: "Paatii", kanji: "パーティー", eng: "Party" },
        { dict: "Biza", kanji: "ビザ", eng: "Visa" },
        { dict: "Takushii", kanji: "タクシー", eng: "Taxi" },
        { dict: "Basu", kanji: "バス", eng: "Bus" },
        { dict: "Meeru", kanji: "メール", eng: "Email / Message" },
        { dict: "Peeji", kanji: "ページ", eng: "Page" },
        { dict: "Nooto", kanji: "ノート", eng: "Notebook" },
        { dict: "Pen", kanji: "ペン", eng: "Pen" },
        { dict: "Karendaa", kanji: "カレンダー", eng: "Calendar" }
    ],
    
    family: [
    // --- General / Collective Terms ---
    { dict: "Kazoku", kanji: "家族", eng: "Family" },
    { dict: "Shinseki", kanji: "親戚", eng: "Relatives" },
    { dict: "Ryoujin / Ryoushin", kanji: "両親", eng: "Parents" },
    { dict: "Kodomo", kanji: "子供", eng: "Child / Children" },
    { dict: "Kyoudai", kanji: "兄弟", eng: "Siblings / Brothers" },
    { dict: "Shimai", kanji: "姉妹", eng: "Sisters" },

    // --- My Family (Humble Terms) ---
    { dict: "Chichi", kanji: "父", eng: "Father (my)" },
    { dict: "Haha", kanji: "母", eng: "Mother (my)" },
    { dict: "Ani", kanji: "兄", eng: "Older brother (my)" },
    { dict: "Ane", kanji: "姉", eng: "Older sister (my)" },
    { dict: "Otouto", kanji: "弟", eng: "Younger brother (my)" },
    { dict: "Imouto", kanji: "妹", eng: "Younger sister (my)" },
    { dict: "Ootto / Sh主人", kanji: "夫", eng: "Husband (my)" },
    { dict: "Tsuma / Kanai", kanji: "妻", eng: "Wife (my)" },
    { dict: "Musuko", kanji: "息子", eng: "Son (my)" },
    { dict: "Musume", kanji: "娘", eng: "Daughter (my)" },
    { dict: "Sobu", kanji: "祖父", eng: "Grandfather (my)" },
    { dict: "Sobo", kanji: "祖母", eng: "Grandmother (my)" },
    { dict: "Mago", kanji: "孫", eng: "Grandchild (my)" },
    { dict: "Oji", kanji: "叔父", eng: "Uncle (my)" },
    { dict: "Oba", kanji: "叔母", eng: "Aunt (my)" },
    { dict: "Itoko", kanji: "従兄弟", eng: "Cousin" },

    // --- Someone Else's Family / Polite Forms ---
    { dict: "Otousan", kanji: "お父さん", eng: "Father (someone else's / address)" },
    { dict: "Okaasan", kanji: "お母さん", eng: "Mother (someone else's / address)" },
    { dict: "Oniisan", kanji: "お兄さん", eng: "Older brother (someone else's)" },
    { dict: "Oneesan", kanji: "お姉さん", eng: "Older sister (someone else's)" },
    { dict: "Otoutosan", kanji: "弟さん", eng: "Younger brother (someone else's)" },
    { dict: "Imoutosan", kanji: "妹さん", eng: "Younger sister (someone else's)" },
    { dict: "Goshujin", kanji: "ご主人", eng: "Husband (someone else's)" },
    { dict: "Okusan", kanji: "奥さん", eng: "Wife (someone else's)" },
    { dict: "Musukosan", kanji: "息子さん", eng: "Son (someone else's)" },
    { dict: "Ojousan", kanji: "お嬢さん", eng: "Daughter (someone else's)" },
    { dict: "Ojiisan", kanji: "おじいさん", eng: "Grandfather (someone else's)" },
    { dict: "Obaasan", kanji: "おばあさん", eng: "Grandmother (someone else's)" },
    { dict: "Ojisan", kanji: "叔父さん", eng: "Uncle (someone else's)" },
    { dict: "Obasan", kanji: "叔母さん", eng: "Aunt (someone else's)" }
]

    
};

window.studyData = studyData;
